### ISSUE TITLE
Download bug

### ISSUE THREAD

**Issue by Clupai8o0** [DHRUV-CODER/Web-Server#1]
I'm not sure if it's for all files but whilst I was trying to download some procreate files from my pc to my device, I needed to change the file name with '_' in between in order for it to work. Is it a bug or a feature? 😂 Or I think it may be because of the '&' instead

**Comment by dhruv-programmes** [comment]
`(Bug or a feature?)` **None** , I tried to recreate the bug , It seems to work perfectly fine . Maybe it is has something to do with the file extension , if the issue persists , please mention the steps to recreate it and check for issues with that particular file. 

Hope it helps.
